CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category_id INTEGER NOT NULL,
    proteins REAL,
    fats REAL,
    carbohydrates REAL,
    calories REAL,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

INSERT INTO categories (id, name) VALUES (1, 'Хлебобулочные изделия, мука, крупы, бобовые');
INSERT INTO categories (id, name) VALUES (2, 'Молочные продукты');
INSERT INTO categories (id, name) VALUES (3, 'Мясные продукты, птица');
INSERT INTO categories (id, name) VALUES (4, 'Колбасные изделия, мясные консервы');
INSERT INTO categories (id, name) VALUES (5, 'Рыба и морепродукты');
INSERT INTO categories (id, name) VALUES (6, 'Яйцепродукты');
INSERT INTO categories (id, name) VALUES (7, 'Масла, жиры и жировые продукты');
INSERT INTO categories (id, name) VALUES (8, 'Овощи, картофель, зелень, грибы, овощные консервы');
INSERT INTO categories (id, name) VALUES (9, 'Фрукты, ягоды, бахчевые');
INSERT INTO categories (id, name) VALUES (10, 'Орехи, семена, сухофрукты');
INSERT INTO categories (id, name) VALUES (11, 'Сахар, сладкое и кондитерские изделия');
INSERT INTO categories (id, name) VALUES (12, 'Соки, напитки безалкогольные');
INSERT INTO categories (id, name) VALUES (13, 'Напитки алкогольные');

INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Продукты г         г          г           ккал Хлеб пшеничный из муки высшего сорта', 1, 7.55, 1.85, 50.3, 248.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлеб пшеничный из муки 1 сорта', 1, 7.6, 0.9, 49.7, 226.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлеб из ржано-пшеничной муки', 1, 6.8, 1.2, 46.4, 215.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлеб ржаной', 1, 4.7, 0.7, 49.8, 214.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлеб "Бородинский"', 1, 6.9, 1.3, 40.9, 208.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('дробленое) Хлеб цельнозерновой из смеси злаков', 1, 13.3, 4.2, 43.3, 265.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлебцы Dr.Körner "Семь злаков"', 1, 10.0, 2.0, 57.0, 290.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлебцы Dr.Körner "Бородинские"', 1, 11.0, 3.0, 52.0, 280.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлебцы Dr.Körner "Гречневые" с витаминами', 1, 11.6, 3.0, 52.4, 283.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хлебцы Dr.Körner "Рисовые" с витаминами', 1, 6.0, 1.0, 69.0, 310.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сдоба', 1, 7.7, 9.5, 63.65, 359.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сухари из пшеничной муки', 1, 11.2, 1.4, 72.4, 331.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука пшеничная из твердых сортов в/с', 1, 10.8, 1.3, 69.9, 334.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука пшеничная в/с', 1, 10.3, 1.1, 70.6, 334.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука пшеничная 1 сорта', 1, 10.6, 1.3, 69.0, 330.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука пшеничная 2 сорта', 1, 11.6, 1.8, 64.8, 322.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука пшеничная обойная', 1, 11.5, 2.2, 61.5, 312.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука ржаная сеяная', 1, 6.9, 1.4, 66.3, 305.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука ржаная обдирная', 1, 8.9, 1.7, 61.8, 298.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мука ржаная обойная', 1, 10.7, 1.9, 58.5, 294.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Макаронные изделия из муки твердых сортов в/с', 1, 11.0, 1.3, 70.5, 338.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('в/с, вареные Макаронные изделия в/с', 1, 10.4, 1.1, 69.7, 337.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Макаронные изделия в/с,вареные', 1, 3.5, 0.4, 23.2, 112.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крупа гречневая ядрица', 1, 12.6, 3.3, 57.1, 308.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гречка вареная', 1, 4.1, 1.0, 18.5, 100.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гречневый продел', 1, 9.5, 2.3, 60.4, 300.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гречка зеленая ("Мистраль")', 1, 13.4, 3.0, 68.0, 328.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис белый шлифованный', 1, 7.0, 1.0, 74.0, 333.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис белый шлифованныйвареный', 1, 2.3, 0.2, 28.7, 130.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис длиннозерный нешлифованный', 1, 7.5, 2.0, 73.0, 340.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис нешлифованный вареный', 1, 2.5, 0.9, 23.0, 112.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис красный нешлифованный', 1, 7.5, 3.0, 68.0, 330.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис дикий черный (цицания водная)', 1, 14.7, 1.1, 68.7, 357.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рис дикий черный вареный', 1, 4.0, 0.3, 19.5, 101.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пшено', 1, 11.5, 3.3, 66.5, 342.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пшено вареное', 1, 3.5, 1.1, 23.6, 119.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крупа овсяная', 1, 12.3, 6.1, 59.5, 342.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Овсяные хлопья', 1, 12.3, 6.2, 61.8, 352.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Каша из овсяных хлопьев на воде', 1, 3.0, 1.7, 15.0, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Каша из овсяных хлопьев на молоке', 1, 3.2, 4.1, 14.2, 102.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Толокно овсяное', 1, 12.5, 6.0, 64.9, 363.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Перловая крупа', 1, 9.3, 1.1, 66.9, 315.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Перловая крупа вареная', 1, 3.1, 0.4, 22.2, 109.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ячневая крупа', 1, 10.0, 1.3, 65.4, 313.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ячневая крупа вареная', 1, 2.3, 0.3, 15.7, 76.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крупа пшеничная "Полтавская"', 1, 11.5, 1.3, 67.9, 329.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крупа пшеничная "Полтавская"вареная', 1, 2.7, 0.3, 15.0, 75.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кукуруза, зерно продовольственное', 1, 10.3, 4.9, 60.0, 325.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кукурузная крупа', 1, 8.3, 1.2, 71.0, 328.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Манная крупа', 1, 10.3, 1.0, 70.6, 333.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Манная каша на воде', 1, 2.5, 0.2, 16.8, 80.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Манная каша на молоке', 1, 3.0, 3.2, 15.3, 98.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горох зерно', 1, 20.5, 2.0, 49.5, 298.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горох целый шлифованный', 1, 22.0, 2.0, 57.0, 330.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горох колотый', 1, 23.0, 1.6, 48.1, 299.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горох вареный', 1, 8.3, 0.4, 21.0, 118.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горошек зеленый свежий', 1, 5.0, 0.2, 8.3, 55.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Маш', 1, 23.9, 1.2, 62.6, 347.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Маш вареный', 1, 7.0, 0.4, 19.2, 105.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Нут', 1, 20.5, 4.3, 63.0, 360.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Нут вареный', 1, 8.9, 2.6, 27.4, 164.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Соя зерно', 1, 36.7, 17.8, 17.3, 364.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Соевые бобы', 1, 36.4, 19.9, 30.1, 446.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Соевые бобы вареные', 1, 16.6, 8.9, 9.9, 173.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фасоль обыкновенная красная, все виды', 1, 23.5, 0.8, 60.0, 333.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фасоль красная вареная', 1, 8.7, 0.5, 22.8, 127.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фасоль стручковая', 1, 2.5, 0.3, 3.0, 23.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чечевица', 1, 24.6, 1.1, 63.4, 352.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чечевица вареная', 1, 9.0, 0.4, 20.1, 116.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чечевица красная', 1, 21.6, 1.1, 48.0, 314.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('("Мистраль") Амарант крупа', 1, 13.6, 7.0, 58.6, 371.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Амарант вареный', 1, 3.8, 1.6, 16.6, 102.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Киноа крупа', 1, 14.1, 6.1, 57.2, 368.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Киноа вареная', 1, 4.4, 1.9, 18.5, 120.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Молоко коровье нежирное', 2, 3.0, 0.05, 4.9, 32.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Молоко 1,5% жирности', 2, 3.0, 1.5, 4.8, 45.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Молоко 2,5%', 2, 2.9, 2.5, 4.8, 54.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Молоко 3,2%', 2, 2.9, 3.2, 4.7, 60.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сливки 10%', 2, 2.7, 10.0, 4.4, 119.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сливки 20%', 2, 2.5, 20.0, 4.0, 205.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Творог нежирный', 2, 22.0, 0.6, 3.3, 110.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Творог 5%', 2, 21.0, 5.0, 3.0, 145.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Творог 9%', 2, 18.0, 9.0, 3.0, 169.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Творог 18%', 2, 15.0, 18.0, 2.8, 236.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сметана 10%', 2, 2.7, 10.0, 3.9, 119.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сметана 20%', 2, 2.5, 20.0, 3.4, 206.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сметана 30%', 2, 2.3, 30.0, 3.1, 293.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кефир нежирный', 2, 3.0, 0.05, 4.0, 31.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кефир 1%', 2, 3.0, 1.0, 4.0, 40.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кефир 2,5%', 2, 2.9, 2.5, 4.0, 53.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кефир 3,2%', 2, 2.9, 3.2, 4.0, 59.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Брынза из коровьего молока', 2, 22.1, 19.2, 0.4, 262.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Адыгейский"', 2, 19.8, 19.8, 1.5, 264.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Гауда"', 2, 25.0, 27.0, 2.0, 356.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Голландский" брусковый', 2, 26.0, 26.8, NULL, 352.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Голландский" круглый', 2, 23.7, 30.4, NULL, 375.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Ламбер"', 2, 23.7, 30.5, NULL, 377.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Ламбер" сливочный', 2, 23.7, 32.5, NULL, 395.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Маасдам"', 2, 23.5, 26.0, NULL, 350.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр моцарелла из цельного молока', 2, 22.2, 22.3, 2.2, 300.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Пармезан"', 2, 37.8, 27.3, 3.4, 415.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Российский"', 2, 23.2, 29.5, NULL, 364.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр рикотта из цельного молока', 2, 11.3, 13.0, 3.0, 174.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сулугуни', 2, 20.5, 22.0, 0.4, 286.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Тильзитер"', 2, 24.4, 26.0, 1.9, 340.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Фета"', 2, 14.2, 21.3, 4.0, 264.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Эдам"', 2, 25.0, 27.8, 1.4, 357.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр плавленый', 2, 16.8, 11.2, 23.8, 257.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыр "Viola"', 2, 11.0, 28.0, 2.0, 305.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Йогурт "Активиа" разных видов', 2, 4.15, 3.2, 14.9, 102.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Йогурт греческий', 2, 6.0, 4.6, 3.85, 83.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('"Actimel" разных видов', 2, 2.8, 8.3, 11.25, 73.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Говядина 1 категории', 3, 18.6, 16.0, NULL, 218.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Говядина 2 категории', 3, 20.0, 9.8, NULL, 168.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Говядина, вырезка', 3, 22.2, 7.1, NULL, 158.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Телятина 1 категории', 3, 19.7, 2.0, NULL, 97.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Свинина жирная', 3, 11.7, 49.3, NULL, 491.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Свинина мясная', 3, 14.3, 33.3, NULL, 357.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Свинина, вырезка', 3, 19.4, 7.1, NULL, 142.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Баранина 1 категории', 3, 15.6, 16.3, NULL, 209.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Баранина 2 категории', 3, 19.8, 9.6, NULL, 166.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Конина', 3, 20.2, 7.0, NULL, 187.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Язык говяжий', 3, 16.0, 12.1, 2.2, 173.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Язык свиной', 3, 15.9, 16.0, 2.1, 208.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Печень говяжья', 3, 17.9, 3.7, 5.3, 127.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Печень свиная', 3, 18.8, 3.8, 4.7, 109.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сердце говяжье', 3, 16.0, 3.5, 2.0, 96.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Почки говяжьи', 3, 15.2, 2.8, 1.9, 86.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вымя', 3, 12.3, 13.7, NULL, 173.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Бройлеры (цыплята) 1 кат.', 3, 18.7, 16.1, NULL, 220.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Бройлеры (цыплята) 2 кат.', 3, 19.7, 11.2, NULL, 180.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Курица 1 кат.', 3, 18.2, 18.4, NULL, 238.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Курица 2 кат.', 3, 21.2, 8.2, NULL, 159.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Куриная грудка', 3, 23.6, 1.9, NULL, 113.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Куриные окорочка', 3, 16.8, 10.2, NULL, 158.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Куриная печень', 3, 19.1, 6.3, 0.6, 136.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Куриное сердце', 3, 15.8, 10.3, 0.8, 159.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Индейка', 3, 19.5, 22.0, NULL, 276.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Индейка, грудка', 3, 23.6, 1.5, NULL, 114.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Индейка, фарш', 3, 20.0, 8.0, 0.5, 161.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гусь домашний, мясо и кожа', 3, 15.5, 36.3, NULL, 391.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гусь домашний, мясо', 3, 22.7, 7.1, NULL, 161.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Перепел, мясо и кожа', 3, 19.6, 12.0, NULL, 192.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Утка домашняя, мясо и кожа', 3, 15.8, 38.0, NULL, 405.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Утка дикая, мясо и кожа', 3, 17.4, 15.2, NULL, 211.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Утка дикая, мясо', 3, 19.8, 4.3, NULL, 123.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Страусиное мясо', 3, 21.8, 2.3, NULL, 114.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фазан, мясо и кожа', 3, 22.7, 9.3, NULL, 181.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фазан, грудка', 3, 24.3, 3.2, NULL, 133.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кролик', 3, 21.2, 11.0, NULL, 183.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кабан', 3, 21.5, 3.3, NULL, 122.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лось', 3, 23.0, 1.5, NULL, 111.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Оленина', 3, 19.5, 8.5, NULL, 155.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса вареная "Диетическая"', 4, 12.1, 13.5, NULL, 170.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> "Докторская"', 4, 12.8, 22.2, 1.5, 257.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> "Любительская"', 4, 12.2, 28.0, 0.1, 301.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> "Молочная"', 4, 11.7, 22.8, 0.2, 252.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> "Московская"', 4, 11.5, 21.8, 2.0, 250.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> "Русская"', 4, 11.5, 27.9, 1.7, 302.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса варено-копченая "Московская"', 4, 19.1, 36.6, 0.2, 406.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> "Сервелат"', 4, 16.1, 40.1, NULL, 425.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса полукопченая "Краковская"', 4, 16.2, 44.6, NULL, 466.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса полукопченая "Одесская"', 4, 14.8, 38.1, 0.3, 402.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса сырокопченая "Брауншвейгская"', 4, 27.7, 42.2, 0.2, 491.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса сырокопченая "Московская"', 4, 24.8, 41.5, NULL, 473.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса сырокопченая свиная', 4, 13.0, 57.0, 0.2, 566.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса сырокопченая "Зернистая"', 4, 9.9, 62.8, 0.3, 606.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Колбаса ливерная', 4, 14.4, 28.5, 2.2, 326.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грудинка сырокопченая', 4, 8.9, 63.3, NULL, 605.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Корейка сырокопченая', 4, 10.5, 47.4, NULL, 469.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ветчина рубленая', 4, 16.3, 20.7, 1.8, 263.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сосиски "Молочные"', 4, 11.0, 23.9, 0.4, 261.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> говяжьи', 4, 10.4, 20.1, 0.8, 226.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> свиные', 4, 9.5, 34.3, NULL, 342.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('>> куриные', 4, 10.8, 22.4, 4.2, 259.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сардельки говяжьи', 4, 11.4, 18.2, 1.3, 215.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шпикачки', 4, 10.0, 33.0, NULL, 337.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Говядина тушеная консервированная', 4, 16.8, 17.0, 0.2, 220.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Свинина тушеная консервированная', 4, 14.9, 32.2, 0.2, 349.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Аргентина', 5, 17.6, 2.0, NULL, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Амур белый', 5, 18.6, 5.3, NULL, 134.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Бычок', 5, 17.5, 2.0, NULL, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вобла', 5, 18.0, 2.8, NULL, 95.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горбуша', 5, 20.5, 6.5, NULL, 140.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Дорадо', 5, 18.0, 3.0, NULL, 96.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Зубатка пестрая', 5, 19.6, 5.3, NULL, 126.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кальмар', 5, 18.0, 2.2, 2.0, 100.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Камбала дальневосточная', 5, 15.7, 3.0, NULL, 90.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Карась', 5, 17.7, 1.8, NULL, 87.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Карп', 5, 16.0, 5.3, NULL, 112.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кета', 5, 19.0, 5.6, NULL, 127.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кефаль', 5, 21.0, 0.4, NULL, 124.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кижуч', 5, 21.6, 5.9, NULL, 146.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Килька балтийская', 5, 14.1, 9.0, NULL, 137.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Килька каспийская', 5, 18.5, 13.1, NULL, 192.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Китовое мясо', 5, 22.5, 3.2, NULL, 119.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Краб камчатский, мясо', 5, 18.2, 1.0, NULL, 82.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Креветки', 5, 19.5, 1.1, NULL, 88.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лангуст', 5, 18.8, 1.3, 0.5, 89.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лангуст вареный', 5, 20.5, 0.7, 0.3, 90.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ледяная рыба', 5, 15.5, 1.4, NULL, 75.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лемонема', 5, 15.9, 0.4, NULL, 67.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лещ', 5, 17.1, 4.1, NULL, 105.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лобстер', 5, 18.8, 0.9, 0.5, 90.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лосось атлантический (семга)', 5, 20.0, 8.1, NULL, 153.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лосось', 5, 19.8, 6.3, NULL, 142.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Макрурус', 5, 13.2, 0.8, NULL, 60.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мидии', 5, 11.5, 2.0, 3.3, 77.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Минтай', 5, 15.9, 0.9, NULL, 72.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мойва весенняя', 5, 13.1, 7.1, NULL, 116.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мойва осенняя', 5, 13.6, 18.1, NULL, 217.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Молоки рыб', 5, 16.0, 2.9, NULL, 90.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Морской гребешок', 5, 17.0, 2.0, 3.0, 92.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Навага', 5, 19.2, 1.6, NULL, 91.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Налим', 5, 18.8, 0.6, NULL, 81.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Нерка красная', 5, 20.3, 8.4, NULL, 157.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Окунь морской', 5, 18.2, 3.3, NULL, 103.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Окунь речной', 5, 18.5, 0.9, NULL, 82.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Омар', 5, 18.8, 1.3, 0.5, 89.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Омар вареный', 5, 20.5, 0.7, 0.3, 90.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Осетр каспийский', 5, 16.4, 10.9, NULL, 164.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Осетр', 5, 15.8, 15.4, NULL, 202.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Палтус белокорый', 5, 18.9, 3.0, NULL, 103.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пангасиус', 5, 15.3, 3.0, NULL, 89.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пикша', 5, 17.2, 0.5, NULL, 73.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Плотва', 5, 17.5, 2.0, NULL, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Путассу', 5, 18.5, 0.9, NULL, 82.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рак речной', 5, 15.5, 1.0, 1.2, 76.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рак речной вареный', 5, 20.3, 1.3, 1.0, 97.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рапана', 5, 16.7, 1.1, NULL, 77.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сазан', 5, 18.2, 2.7, NULL, 97.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь атлантическая нежирная', 5, 19.1, 6.5, NULL, 135.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь атлантическая жирная', 5, 17.7, 19.5, NULL, 248.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь тихоокеанская нежирная', 5, 18.0, 7.0, NULL, 135.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь тихоокеанская жирная', 5, 14.0, 15.0, NULL, 191.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семга', 5, 21.6, 6.0, NULL, 140.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семга брюшки', 5, 25.0, 24.0, NULL, 310.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Скумбрия атлантическая', 5, 18.0, 13.2, NULL, 191.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Скумбрия', 5, 18.7, 11.9, NULL, 181.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сом', 5, 17.2, 5.1, NULL, 115.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ставрида океаническая', 5, 18.5, 4.5, NULL, 114.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Стерлядь', 5, 17.0, 6.1, NULL, 122.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Судак', 5, 18.4, 1.1, NULL, 84.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Терпуг', 5, 17.8, 3.4, NULL, 102.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тилапия', 5, 20.1, 1.7, NULL, 96.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Треска атлантическая', 5, 17.8, 0.7, NULL, 82.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Треска тихоокеанская', 5, 15.3, 0.4, NULL, 69.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тунец голубой', 5, 23.3, 4.9, NULL, 144.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тунец желтоперый (желтохвостый)', 5, 24.4, 0.5, NULL, 109.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Устрица', 5, 9.0, 2.0, 4.5, 72.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Форель', 5, 19.2, 2.1, NULL, 97.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Форель морская', 5, 20.5, 4.3, NULL, 157.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хек', 5, 16.6, 2.2, NULL, 86.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Щука', 5, 18.4, 1.1, NULL, 84.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Язык морской', 5, 10.3, 5.2, NULL, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Язь', 5, 18.2, 1.0, NULL, 81.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рыба соленая, копченая, вяленая, икра Вобла вяленая', 5, 46.4, 5.5, NULL, 235.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горбуша горячего копчения', 5, 23.2, 7.6, NULL, 161.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горбуша соленая', 5, 22.1, 9.0, NULL, 169.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кальмары сушеные', 5, 62.0, 2.0, 5.0, 286.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кета соленая', 5, 24.3, 9.6, NULL, 184.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Килька балтийская горячего копчения', 5, 21.3, 8.5, NULL, 162.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Килька балтийская соленая', 5, 17.1, 7.6, NULL, 137.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Килька пряного посола', 5, 14.8, 10.5, NULL, 154.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крабовые палочки', 5, 6.6, 0.54, 13.1, 82.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра красная лососевая', 5, 32.0, 15.0, NULL, 263.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра минтая пробойная', 5, 27.9, 1.8, 1.1, 132.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра мойвы "Санта Бремор"', 5, 8.7, 37.75, NULL, 373.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра сельди', 5, 31.6, 10.3, NULL, 222.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра черная осетровая зернистая', 5, 28.4, 9.3, 0.6, 200.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра осетровая паюсная', 5, 38.2, 14.5, 1.5, 289.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра щучья', 5, 17.3, 2.0, NULL, 87.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лосось соленый', 5, 21.0, 20.5, NULL, 269.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лещ вяленый', 5, 42.0, 5.9, NULL, 221.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лещ горячего копчения', 5, 32.8, 4.5, NULL, 172.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лещ холодного копчения', 5, 29.7, 4.6, NULL, 160.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масляная рыба копченая', 5, 18.0, 12.0, NULL, 180.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мойва копченая', 5, 18.0, 22.0, NULL, 270.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Окунь морской горячего копчения', 5, 23.5, 8.0, NULL, 166.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Осетр холодного копчения, балык', 5, 20.4, 12.5, NULL, 194.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Салака копченая', 5, 25.4, 5.6, NULL, 152.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь горячего копчения', 5, 21.8, 14.3, NULL, 215.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь атлантическая среднесоленая', 5, 17.0, 8.5, NULL, 145.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь тихоокеанская среднесоленая', 5, 17.4, 17.1, NULL, 224.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь соленая', 5, 19.8, 15.4, NULL, 217.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семга соленая потрошеная с головой', 5, 22.5, 12.5, NULL, 202.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семга копченая', 5, 22.5, 12.5, NULL, 202.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Скумбрия горячего копчения', 5, 22.1, 23.8, NULL, 307.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Скумбрия холодного копчения', 5, 23.4, 6.4, NULL, 150.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Форель копченая', 5, 26.0, 3.1, 0.5, 132.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Форель слабосоленая', 5, 20.6, 10.1, NULL, 186.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Форель слабосоленая жирная', 5, 23.0, 15.0, NULL, 227.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хамса соленая', 5, 21.2, 9.0, NULL, 166.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Консервы рыбные Бычки в томатном соусе', 5, 17.5, 2.0, NULL, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горбуша натуральная', 5, 20.9, 5.8, NULL, 136.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горбуша в томатном соусе', 5, 15.0, 6.0, 4.1, 130.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кальмары', 5, 15.25, 1.2, 2.4, 84.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Килька в томатном соусе', 5, 14.0, 12.0, 4.5, 182.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крабы', 5, 18.7, 1.1, 0.1, 85.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Морская капуста', 5, 0.8, 5.1, NULL, 49.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Печень минтая', 5, 6.0, 50.0, NULL, 474.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Печень трески', 5, 4.2, 65.7, 1.2, 613.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сайра бланшированная в масле', 5, 18.3, 23.3, NULL, 283.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сардины с добавлением масла', 5, 19.0, 18.0, NULL, 238.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сардины в масле', 5, 24.1, 13.9, NULL, 221.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сардины в томатном соусе', 5, 17.0, 9.9, 1.4, 162.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь', 5, 17.5, 2.0, NULL, 88.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдь в растительном масле', 5, 16.4, 26.5, NULL, 301.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Скумбрия натуральная', 5, 17.7, 14.4, NULL, 200.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Скумбрия в масле', 5, 14.4, 28.9, NULL, 318.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ставрида в масле', 5, 15.6, 27.4, NULL, 309.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ставрида в томатном соусе', 5, 14.8, 2.3, 73.0, 110.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тунец натуральный', 5, 22.5, 0.7, NULL, 96.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тунец в масле', 5, 22.0, 15.9, NULL, 232.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шпроты в масле', 5, 17.4, 32.4, 0.4, 363.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шпротный паштет', 5, 12.0, 14.0, 5.3, 195.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо куриное', 6, 12.7, 10.9, 0.7, 157.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Белок', 6, 11.1, NULL, NULL, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Желток', 6, 16.2, 31.2, 1.0, 354.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо куриное отварное', 6, 12.7, 11.5, 0.7, 157.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо куриное жареное без масла', 6, 14.6, 12.6, 0.8, 174.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо перепелиное', 6, 11.9, 13.1, 0.6, 168.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо гусиное', 6, 13.9, 13.3, 1.4, 185.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо утиное', 6, 13.3, 14.5, 0.1, 185.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яйцо страусиное', 6, 12.2, 11.7, 0.7, 118.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Меланж', 6, 12.7, 11.5, 0.7, 157.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яичный порошок', 6, 46.0, 37.3, 4.5, 542.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масло сливочное', 7, 0.75, 80.25, 0.8, 728.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масло сливочное "Валио"', 7, 0.7, 82.0, 0.7, 740.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масло топленое', 7, 0.2, 99.0, NULL, 892.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масло шоколадное', 7, 1.5, 62.0, 18.6, 642.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масло оливковое', 7, NULL, 99.8, NULL, 898.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Масло подсолнечное', 7, NULL, 99.9, NULL, 899.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Маргарин', 7, 0.4, 82.25, 0.75, 744.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Спред', 7, NULL, 40.0, NULL, 360.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Майонез', 7, 2.25, 59.5, 3.25, 557.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Майонез легкий', 7, 0.85, 19.0, 4.2, 205.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Жир говяжий, свиной, бараний топленые', 7, NULL, 99.7, NULL, 897.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Жир кулинарный, кондитерский', 7, NULL, 99.7, NULL, 897.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Жир рыбий', 7, NULL, 100.0, NULL, 902.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сало', 7, 2.4, 89.0, NULL, 797.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шпик', 7, 1.4, 92.8, NULL, 841.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Артишок', 8, 1.2, 0.1, 6.0, 28.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Базилик', 8, 2.5, 0.6, 4.3, 27.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Баклажаны', 8, 1.2, 0.1, 4.5, 24.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Батат (сладкий картофель)', 8, 1.6, 0.05, 17.1, 86.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Батат отварной без кожуры', 8, 1.4, 0.14, 15.2, 76.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Брюква', 8, 1.2, 0.1, 7.7, 37.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горчица листовая', 8, 2.9, 0.4, 1.5, 27.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Дайкон', 8, 1.2, NULL, 4.1, 21.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Имбирь, корень сырой', 8, 1.8, 0.75, 15.8, 80.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кабачки', 8, 0.6, 0.3, 4.6, 24.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста белокочанная', 8, 1.8, 0.1, 4.7, 28.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста квашеная', 8, 1.8, 0.1, 3.0, 23.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста вареная', 8, 1.4, 0.1, 4.2, 24.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста брокколи', 8, 2.8, 0.37, 6.6, 34.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста брокколи вареная', 8, 2.38, 0.4, 7.18, 35.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста брокколизамороженная, вареная', 8, 3.1, 0.12, 5.35, 28.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста брюссельская', 8, 3.4, 0.3, 8.9, 43.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста брюссельскаязамороженная, вареная', 8, 3.6, 0.4, 8.3, 42.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста кольраби', 8, 2.8, 0.1, 7.9, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста краснокочанная', 8, 0.8, 0.2, 5.1, 26.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста пекинская', 8, 1.2, 0.2, 2.0, 16.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста савойская', 8, 1.2, 0.1, 5.6, 28.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста цветная', 8, 2.5, 0.3, 4.2, 30.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста листовая кале (кейл, Kale)', 8, 2.8, 0.6, 6.6, 42.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Капуста листовая коллардс(Collards)', 8, 3.0, 0.6, 1.4, 32.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Картофель', 8, 2.0, 0.4, 16.3, 77.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Картофель отварной', 8, 2.0, 0.4, 15.8, 75.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кресс-салат', 8, 2.3, 0.1, 0.8, 11.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кукуруза сырая', 8, 3.3, 1.35, 16.7, 86.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лук зеленый', 8, 1.3, 0.1, 3.2, 20.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лук репчатый', 8, 1.4, 0.2, 8.2, 41.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лук репчатый красный', 8, 1.4, 0.1, 9.1, 42.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лук порей', 8, 2.0, 0.2, 6.3, 36.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мангольд', 8, 1.8, 0.2, 2.1, 19.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Морковь', 8, 1.3, 0.1, 6.9, 35.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Морковь отварная', 8, 1.3, 0.1, 6.4, 33.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Огурцы грунтовые', 8, 0.8, 0.1, 2.5, 14.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Огурцы тепличные', 8, 0.7, 0.1, 1.9, 11.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Огурцы соленые', 8, 0.8, 0.1, 1.7, 13.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пастернак корень', 8, 1.4, 0.5, 9.2, 47.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Патиссон', 8, 0.6, 0.1, 4.1, 19.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Перец сладкий', 8, 1.3, 0.1, 4.9, 26.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Петрушка зелень', 8, 3.7, 0.4, 7.6, 49.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Петрушка корень', 8, 1.5, 0.6, 10.1, 51.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Помидоры грунтовые', 8, 1.1, 0.2, 3.8, 24.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Помидоры тепличные', 8, 0.9, 0.1, 2.9, 17.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Помидоры черри', 8, 0.8, 0.1, 2.8, 15.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Помидоры соленые', 8, 0.5, 0.1, 1.85, 10.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Редис', 8, 1.2, 0.1, 3.4, 20.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Редька зеленая', 8, 2.0, 0.2, 5.6, 32.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Редька черная', 8, 1.9, 0.2, 6.7, 36.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Репа', 8, 1.5, 0.1, 6.2, 32.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Розмарин свежий', 8, 3.3, 5.9, 17.6, 131.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Руккола', 8, 2.6, 0.7, 2.1, 25.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Салат листовой', 8, 1.5, 0.2, 2.0, 16.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Свекла', 8, 1.5, 0.1, 8.8, 42.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Свекла отварная', 8, 1.8, 0.1, 9.8, 48.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдерей зелень', 8, 0.9, 0.1, 2.1, 13.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сельдерей корень', 8, 1.3, 0.3, 6.5, 37.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Спаржа', 8, 1.9, 0.1, 3.1, 21.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тимьян свежий', 8, 5.6, 1.7, 15.9, 101.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Топинамбур', 8, 2.1, 0.1, 12.8, 61.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тыква', 8, 1.0, 0.1, 4.4, 23.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тыква отварная', 8, 1.2, 0.1, 4.9, 26.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Укроп', 8, 2.5, 0.5, 6.3, 40.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хрен', 8, 3.2, 0.4, 10.5, 59.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Цуккини', 8, 1.2, 0.2, 2.7, 17.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чеснок', 8, 6.5, 0.5, 29.9, 149.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шпинат', 8, 2.9, 0.3, 2.0, 23.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Щавель', 8, 1.5, 0.3, 2.9, 22.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Водоросли вакаме (ундария перистая) сырые', 8, 3.0, 0.64, 9.3, 45.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ламинария (морская капуста) сырая', 8, 1.7, 0.56, 8.9, 43.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ламинария (морская капуста) сушеная', 8, 31.5, 21.8, 38.1, 476.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Спирулина сушеная', 8, 57.5, 7.72, 23.4, 290.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грибы Грибы белые свежие', 8, 3.7, 1.7, 1.1, 34.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грибы белые сушеные', 8, 30.3, 14.3, 9.0, 286.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вешенки свежие', 8, 2.5, 0.3, 6.5, 3.8);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грузди свежие', 8, 1.8, 0.5, 0.8, 16.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лисички', 8, 1.5, 1.0, 1.0, 19.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Опята', 8, 2.2, 1.2, 0.5, 22.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Подберезовики', 8, 2.1, 0.8, 1.2, 20.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Подберезовики сушеные', 8, 23.5, 9.2, 14.3, 231.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Подосиновики', 8, 3.3, 0.5, 1.2, 22.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Подосиновики сушеные', 8, 35.4, 5.4, 33.2, 315.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сморчки', 8, 1.7, 0.3, 4.2, 27.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сыроежки', 8, 1.7, 0.7, 1.5, 19.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шампиньоны', 8, 4.3, 1.0, 0.1, 27.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Овощные консервы Икра баклажанная', 8, 1.7, 13.3, 5.1, 148.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Икра кабачковая', 8, 1.6, 8.0, 8.0, 109.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Горошек зеленый', 8, 3.1, 0.2, 6.5, 40.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кукуруза сладкая', 8, 2.95, 0.65, 16.85, 92.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Огурцы маринованные', 8, 0.8, NULL, 1.3, 16.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Помидоры маринованные', 8, 0.5, 0.1, 2.1, 10.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Арбуз', 9, 0.6, 0.1, 5.8, 27.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Абрикосы', 9, 0.9, 0.1, 9.0, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Авокадо', 9, 2.0, 14.6, 8.5, 160.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Айва', 9, 0.6, 0.5, 9.6, 48.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Алыча', 9, 0.2, 0.1, 7.9, 34.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ананас', 9, 0.4, 0.2, 11.5, 52.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Апельсины', 9, 0.9, 0.2, 8.1, 43.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Банан', 9, 1.5, 0.5, 21.0, 96.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Виноград', 9, 0.6, 0.6, 15.4, 72.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вишня', 9, 0.8, 0.2, 10.6, 52.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гранат', 9, 0.7, 0.6, 14.5, 72.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грейпфрут', 9, 0.7, 0.2, 6.5, 35.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Груша', 9, 0.4, 0.3, 10.3, 47.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Дуриан', 9, 1.5, 5.3, 23.3, 147.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Дыня', 9, 0.6, 0.3, 7.4, 35.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Инжир свежий', 9, 0.7, 0.2, 12.0, 54.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Киви', 9, 0.8, 0.4, 8.1, 47.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кумкват', 9, 1.9, 0.9, 13.4, 71.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лимон', 9, 0.9, 0.1, 3.0, 34.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Личи', 9, 0.8, 0.4, 15.2, 66.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Манго', 9, 0.8, 0.4, 13.4, 60.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мандарины', 9, 0.8, 0.2, 7.5, 38.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Маракуйя', 9, 2.4, 0.4, 13.4, 68.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Нектарин', 9, 1.1, 0.3, 9.0, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Папайя', 9, 0.5, 0.26, 9.1, 43.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Персик', 9, 0.9, 0.1, 9.5, 45.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Помело', 9, 0.8, 0.04, 8.6, 38.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Слива', 9, 0.8, 0.3, 9.6, 49.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Терн', 9, 1.5, 0.3, 9.4, 54.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фейхоа', 9, 0.7, 0.4, 8.8, 61.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Хурма', 9, 0.5, 0.4, 15.3, 67.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Черешня', 9, 1.1, 0.4, 10.6, 52.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яблоки', 9, 0.4, 0.4, 9.8, 47.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Брусника', 9, 0.7, 0.5, 8.2, 46.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Голубика', 9, 1.0, 0.5, 6.6, 39.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ежевика', 9, 1.5, 0.5, 4.4, 34.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Клубника', 9, 0.8, 0.4, 7.5, 41.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Клюква', 9, 0.5, 0.2, 3.7, 28.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Крыжовник', 9, 0.7, 0.2, 9.1, 45.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Малина', 9, 0.8, 0.5, 8.3, 46.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Морошка', 9, 0.8, 0.9, 7.4, 40.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Облепиха', 9, 1.2, 5.4, 5.7, 82.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Смородина белая', 9, 0.5, 0.2, 8.0, 42.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Смородина красная', 9, 0.6, 0.2, 7.7, 43.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Смородина черная', 9, 1.0, 0.4, 7.3, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Черника', 9, 1.1, 0.6, 7.6, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шиповник свежий', 9, 1.6, 0.7, 22.4, 109.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шиповник сухой', 9, 3.4, 1.4, 48.3, 284.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Продукты                                         Углеводы, г г        г                     ккал Арахис', 10, 26.3, 45.2, 9.9, 552.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Арахис жареный', 10, 26.0, 52.0, 13.4, 626.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Бразильский орех', 10, 14.3, 67.1, 4.2, 659.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грецкие орехи', 10, 16.2, 60.8, 11.1, 656.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кедровые орехи', 10, 13.7, 64.1, 9.4, 673.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кешью', 10, 18.5, 48.5, 22.5, 600.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кешью жареный', 10, 17.5, 42.2, 30.5, 572.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кокосовый орех сырой', 10, 3.3, 33.5, 6.2, 354.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лесной орех (лещина)', 10, 13.0, 62.6, 9.3, 653.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Миндальный орех', 10, 18.6, 53.7, 13.0, 609.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Миндальный орех жареный', 10, 22.4, 55.9, 12.3, 642.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Миндальные лепестки', 10, 22.0, 58.0, 12.0, 650.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Орех макадамия', 10, 7.9, 75.8, 5.2, 718.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Орехи пекан', 10, 9.2, 72.0, 4.3, 691.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семечки подсолнечника, ядра сушеные', 10, 20.8, 51.5, 17.4, 584.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семечки тыквенные, ядра сушеные', 10, 30.2, 49.1, 9.3, 559.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семена конопли очищенные', 10, 31.6, 48.7, 4.7, 553.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семена конопли неочищенные', 10, 20.1, 32.5, 14.0, 429.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семена кунжута', 10, 19.4, 48.7, 12.2, 565.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семена льна', 10, 18.3, 42.2, 1.6, 534.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семена мака', 10, 17.5, 47.5, 14.5, 556.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Семена чиа', 10, 16.5, 30.7, 7.7, 486.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фисташки сырые', 10, 20.2, 45.3, 16.6, 560.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('соли Фундук (лещина окультуренная)', 10, 15.0, 61.5, 9.4, 651.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фундук жареный', 10, 17.8, 66.1, 9.4, 703.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Бананы сушеные', 10, 3.9, 1.8, 78.4, 346.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вишня сушеная', 10, 1.5, NULL, 73.0, 290.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Груша сушеная', 10, 2.3, 0.6, 62.6, 270.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Дыня сушеная', 10, 0.7, 0.1, 82.2, 341.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Изюм', 10, 2.5, 0.54, 67.7, 296.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Изюм кишмиш', 10, 2.3, 0.5, 65.8, 281.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Инжир сушеный', 10, 3.1, 0.8, 57.9, 257.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Курага', 10, 5.2, 0.3, 51.0, 232.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Персик сушеный', 10, 3.0, 0.4, 57.7, 254.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Урюк', 10, 5.0, 0.4, 53.0, 242.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Финики', 10, 2.5, 0.5, 69.2, 292.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чернослив (слива сушеная)', 10, 2.3, 0.7, 57.5, 256.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яблоки сушеные', 10, 2.2, 0.1, 59.0, 253.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сахар-песок', 11, NULL, NULL, 99.8, 399.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сахар-рафинад', 11, NULL, NULL, 99.9, 400.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Сахар тростниковый', 11, NULL, NULL, 99.7, 394.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье вишневое', 11, NULL, NULL, 64.0, 256.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье клубничное', 11, 0.3, NULL, 74.0, 282.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье малиновое', 11, 0.6, NULL, 70.4, 270.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье сливовое', 11, 0.7, NULL, 74.6, 283.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье черничное', 11, 0.4, NULL, 51.6, 211.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье из черной смородины', 11, 0.6, NULL, 72.9, 282.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Варенье яблочное', 11, 0.4, NULL, 68.7, 260.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вафли', 11, 4.35, 16.4, 66.0, 441.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Галеты', 11, 11.0, 1.5, 75.0, 360.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Зефир', 11, 0.85, 0.05, 79.4, 305.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Зефир в шоколаде', 11, 2.0, 10.0, 70.0, 365.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Какао-порошок', 11, 24.3, 15.0, 10.2, 289.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Карамель', 11, 0.4, 0.5, 93.85, 377.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кекс с изюмом', 11, 6.4, 17.6, 53.6, 384.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Козинак из семян подсолнечника', 11, 14.8, 42.6, 34.5, 576.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Конфеты "Белочка"', 11, 8.8, 33.1, 53.4, 538.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Конфеты "Коровка"', 11, 2.7, 4.4, 82.4, 351.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Круассаны', 11, 6.75, 24.25, 44.5, 425.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мармелад', 11, NULL, 0.1, 77.7, 296.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мед натуральный', 11, 0.8, NULL, 80.3, 308.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Молоко сгущенное с сахаром 8,5%, Беларусь', 11, 7.2, 8.5, 56.0, 329.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мороженое молочное', 11, 3.2, 3.5, 21.3, 126.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мороженое пломбир', 11, 3.2, 15.0, 20.8, 227.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Нуга', 11, 6.5, 16.5, 66.0, 435.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Печенье', 11, 8.9, 7.6, 75.9, 395.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Печенье овсяное', 11, 6.5, 14.4, 71.8, 437.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пирожные', 11, 3.0, 18.35, 50.5, 415.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Повидло', 11, 0.35, 0.3, 65.5, 250.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пряники Тульские', 11, 7.25, 7.55, 69.75, 370.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Рахат-лукум', 11, 0.4, 0.35, 80.5, 315.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Торт медовый', 11, 5.7, 27.5, 45.5, 455.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Торт "Наполеон"', 11, 6.15, 37.5, 31.0, 485.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Торт "Полет"', 11, 5.7, 24.8, 55.4, 456.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Торт "Прага"', 11, 5.9, 25.25, 53.5, 465.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Торт "Сказка"', 11, 4.3, 17.1, 46.9, 351.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Торт сметанно-ореховый', 11, 2.9, 13.5, 35.3, 275.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Халва подсолнечная', 11, 11.6, 29.7, 54.0, 516.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чак-чак', 11, 8.6, 1.9, 77.9, 363.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шоколадный батончик "Сникерс"', 11, 9.3, 27.9, 54.6, 507.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шоколад горький', 11, 8.0, 36.0, 46.8, 540.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Шоколад молочный', 11, 6.9, 35.7, 54.4, 550.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Абрикосовый сок', 12, 0.7, 0.05, 10.85, 46.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ананасовый', 12, 0.3, 0.1, 11.4, 48.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Апельсиновый', 12, 0.8, 0.15, 10.65, 48.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Березовый', 12, 0.1, NULL, 5.8, 24.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Виноградный', 12, 0.3, 0.1, 15.15, 62.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Гранатовый', 12, 0.3, 0.1, 14.2, 56.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грейпфрутовый', 12, 0.3, 0.1, 7.2, 33.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Грушевый', 12, 0.4, NULL, 11.0, 45.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лаймовый, свежевыжатый', 12, 0.4, 0.1, 8.0, 25.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лимонный, свежевыжатый', 12, 0.35, 0.24, 6.6, 22.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Манго сок', 12, NULL, NULL, 13.5, 54.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Мандариновый', 12, 0.8, NULL, 8.95, 40.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Морковный', 12, 1.1, 0.1, 9.5, 44.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Персиковый', 12, 0.3, NULL, 13.0, 53.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Томатный', 12, 1.05, 0.15, 3.35, 19.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тыквенный', 12, NULL, NULL, 9.0, 38.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Яблочный', 12, 0.45, 0.1, 9.95, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('7up', 12, NULL, NULL, 8.7, 38.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Квас "Очаковский"', 12, NULL, NULL, 5.5, 30.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Квас хлебный', 12, 0.2, NULL, 5.2, 27.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кока-кола', 12, NULL, NULL, 10.4, 42.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кофе черный зерновой без сахара', 12, 0.2, 0.5, 0.3, 7.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кофе с молоком и сахаром', 12, 0.7, 1.0, 11.2, 58.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Лимонад', 12, NULL, NULL, 6.4, 26.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пепси', 12, NULL, NULL, 8.7, 38.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пиво безалкагольное', 12, NULL, NULL, 5.1, 27.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Тоник', 12, NULL, NULL, 8.3, 34.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Фанта', 12, NULL, NULL, 11.7, 48.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Цикорий растворимый', 12, 0.1, NULL, 2.8, 11.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чай зеленый', 12, NULL, NULL, NULL, NULL);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чай черный без сахара', 12, 0.1, NULL, NULL, NULL);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чай черный с сахаром', 12, 0.1, NULL, 7.0, 28.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чай черный с молоком и сахаром', 12, 0.7, 0.8, 8.2, 43.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Продукты                                                          Углеводы, г г           г                       ккал Вермут Cinzano, Martini', 13, NULL, NULL, 16.25, 146.5);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('ч. игристые Вина виноградные крепкие', 13, 0.4, NULL, 12.0, 163.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Вина виноградные ликерные', 13, 0.5, NULL, 30.0, 212.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Виски', 13, NULL, NULL, 0.4, 235.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Водка', 13, NULL, NULL, 0.4, 235.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Джин', 13, NULL, NULL, NULL, 230.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Джин-тоник', 13, NULL, NULL, 6.7, 78.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Кагор', 13, NULL, NULL, 16.0, 147.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Коньяк', 13, NULL, NULL, 0.1, 239.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ликер Amaretto', 13, NULL, NULL, 35.0, 280.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ликер Baileys', 13, 3.0, 13.0, 25.0, 327.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ликер "Куантро"', 13, NULL, NULL, 20.0, 197.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ликер "Калуа"', 13, 0.6, 0.7, 41.7, 291.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ликер "Малибу"', 13, NULL, NULL, 20.0, 197.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пиво светлое легкое', 13, 0.3, NULL, 5.05, 44.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Пиво темное легкое', 13, 0.3, NULL, 5.7, 48.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Портвейн', 13, 0.4, NULL, 12.0, 163.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Ром', 13, NULL, NULL, NULL, 220.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Саке', 13, 0.5, NULL, 5.0, 134.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Самогон', 13, 0.1, 0.1, 0.4, 235.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Спирт этиловый 96%', 13, 4.0, NULL, 3.8, 710.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Текила', 13, 1.4, 0.3, 24.0, 231.0);
INSERT INTO products (name, category_id, proteins, fats, carbohydrates, calories) VALUES ('Чача', 13, 0.1, 0.1, 0.5, 225.0);
Creating a title is not possible without additional context or content. - Manus